### ISSUE TITLE
provide .regexnb notebooks test examples

### ISSUE THREAD

**Issue by RandomFractals** [jrieken/vscode-regex-notebook#1]
I created this in my fork:

https://github.com/RandomFractals/vscode-regex-notebook/tree/master/notebooks

from: https://regexr.com/3aeb7

I think we could add more patterns from that site for testing.

/notebooks is the standard repo directory in Py & other data sci parlance.

**Comment by RandomFractals** [comment]
hey @jrieken, let's keep this open for now.

I'll add more .regexnb test notebooks from https://regexr.com later this week.

**Comment by jrieken** [comment]
Great
