### ISSUE TITLE
.regexnb dosn't display expression diagram on cell run

### ISSUE THREAD

**Issue by RandomFractals** [jrieken/vscode-regex-notebook#2]
example:

![regexnb-src](https://user-images.githubusercontent.com/656833/94808673-1750c580-03b7-11eb-8d0b-cc2a91192d7c.png)

![regexnb-run](https://user-images.githubusercontent.com/656833/94808694-1ddf3d00-03b7-11eb-88ee-03b4a1f8f4e5.png)

expected:

![regex-diagram](https://user-images.githubusercontent.com/656833/94808853-5b43ca80-03b7-11eb-9400-ee98d0a1c1ec.png)

**Comment by jrieken** [comment]
Misses an API adoption...

**Comment by RandomFractals** [comment]
yeah, thanks for that patch. I did not see an error until I ran the whole notebook with that one cell.

might need a fix for #3 too :(
