### ISSUE TITLE
error loading regexper.js on windows

### ISSUE THREAD

**Issue by RandomFractals** [jrieken/vscode-regex-notebook#3]
![image](https://user-images.githubusercontent.com/656833/94811719-626cd780-03bb-11eb-8ef1-be76c8b329ae.png)

**Comment by jrieken** [comment]
Did you run `npm run compile`?

**Comment by RandomFractals** [comment]
oops. my bad. I just ran npm install. so, it did not gen the dist folder.

anyhoo, we got lift off! :)

![image](https://user-images.githubusercontent.com/656833/94812529-7b29bd00-03bc-11eb-8b98-fccfbf9137cd.png)

**Comment by jrieken** [comment]
Yeah, this extension is still very rough and more less my testbed for what I think is a cool idea

**Comment by RandomFractals** [comment]
np. I like the .regexnb idea & figured would be best place for me to start on learning how to create a custom nb renderer.

Thanks for putting this out & that quick patch to get me up and running.

I'll send you a PR for #1.

**Comment by jrieken** [comment]
> start on learning how to create a custom nb renderer.

btw - use a `launch.config` as here and this user (not workspace) setting: `"webview.experimental.useIframes": true`. It will allow you to debug the renderer with VS Code
